def input_error(func):
    def inner(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except ValueError:
            return "ðŸŸ¡ Give me name and phone please."
        except KeyError:
            return "ðŸŸ¡ Contact does not exist"
        except IndexError:
            return "ðŸŸ¡ Enter contact name"
        except:
            return "ðŸ”´ Some error is occured. We are working on a solution"

    return inner